Eateries/Models/Restaurant.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Common;
namespace Eateries.Models{
public class Restaurant
  {
    public int RestaurantId { get; set;  }
    public string Name {get; set; }
    public string Description { get; set; }
    public int CuisineId { get; set; }
    public Cuisine Cuisine { get; set; }
    public List<RestaurantTag> JoinEntities { get; }
  }
}

Eateries/Controllers/CuisineController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Eateries.Models;
using System.Collections.Generic;
using System.Linq;

namespace Eateries.Controllers
{
  public class CuisineController : Controller
  {
    private readonly EateriesContext _db;

    public CuisineController(EateriesContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Cuisine> model = _db.Cuisine.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Cuisine cuisine)
    {
      _db.Cuisine.Add(cuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Cuisine thisCuisine = _db.Cuisine
                                  .Include(cuisine => cuisine.Restaurants)
                                  .FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(thisCuisine);
    }

    public ActionResult Edit(int id)
    {
      Cuisine thisCuisine = _db.Cuisine.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(thisCuisine);
    }

    [HttpPost]
    public ActionResult Edit(Cuisine cuisine)
    {
      _db.Cuisine.Update(cuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Cuisine thisCuisine = _db.Cuisine.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(thisCuisine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Cuisine thisCuisine = _db.Cuisine.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      _db.Cuisine.Remove(thisCuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Eateries/Controllers/RestaurantsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Eateries.Models;
using System.Collections.Generic;
using System.Linq;

namespace Eateries.Controllers
{
  public class RestaurantsController : Controller
  {
    private readonly EateriesContext _db;

    public RestaurantsController(EateriesContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Restaurant> model = _db.Restaurants
                            .Include(restaurant => restaurant.Cuisine)
                            .ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.CuisineId = new SelectList(_db.Cuisine, "CuisineId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Restaurant restaurant)
    {
      if (restaurant.CuisineId == 0)
      {
        return RedirectToAction("Create");
      }
      _db.Restaurants.Add(restaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants
              .Include(restaurant => restaurant.Cuisine)
              .Include(restaurant => restaurant.JoinEntities)
              .ThenInclude(join => join.Tag)
              .FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      return View(thisRestaurant);
    }

    public ActionResult Edit(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      ViewBag.CuisineId = new SelectList(_db.Cuisine, "CuisineId", "Name");
      return View(thisRestaurant);
    }

    [HttpPost]
    public ActionResult Edit(Restaurant restaurant)
    {
      _db.Restaurants.Update(restaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      return View(thisRestaurant);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      _db.Restaurants.Remove(thisRestaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult AddTag(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurants => restaurants.RestaurantId == id);
      ViewBag.TagId = new SelectList(_db.Tags, "TagId", "Title");
      return View(thisRestaurant);
    }
    [HttpPost]
    public ActionResult AddTag(Restaurant restaurant, int tagId)
    {
      #nullable enable
      RestaurantTag? joinEntity = _db.RestaurantTags.FirstOrDefault(join => (join.TagId == tagId && join.RestaurantId == restaurant.RestaurantId));
      #nullable disable
      if (joinEntity == null && tagId != 0)
      {
        _db.RestaurantTags.Add(new RestaurantTag() { TagId = tagId, RestaurantId = restaurant.RestaurantId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = restaurant.RestaurantId });
    }
    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      RestaurantTag joinEntry = _db.RestaurantTags.FirstOrDefault(entry => entry.RestaurantTagId == joinId);
      _db.RestaurantTags.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Eateries/Controllers/TagsController.cs
using Microsoft.AspNetCore.Mvc;
using Eateries.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Eateries.Controllers
{
  public class TagsController : Controller
  {
    private readonly EateriesContext _db;

    public TagsController(EateriesContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Tags.ToList());
    }

    public ActionResult Details(int id)
    {
      Tag thisTag = _db.Tags
          .Include(tag => tag.JoinEntities)
          .ThenInclude(join => join.Restaurants)
          .FirstOrDefault(tag => tag.TagId == id);
      return View(thisTag);
    }
    public ActionResult Create()
    {
      return View();
    }
    [HttpPost]
    public ActionResult Create(Tag tag)
    {
      _db.Tags.Add(tag);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult AddRestaurant(int id)
    {
      Tag thisTag = _db.Tags.FirstOrDefault(tag => tag.TagId == id);
      ViewBag.RestaurantId = new SelectList(_db.Restaurants, "RestaurantId", "Name");
      return View(thisTag);
    }
    [HttpPost]
    public ActionResult AddRestaurant(Tag tag, int restaurantId)
    {
      #nullable enable
      RestaurantTag? joinEntity = _db.RestaurantTags.FirstOrDefault(join => (join.RestaurantId == restaurantId && join.TagId == tag.TagId));
      #nullable disable
      if (joinEntity == null && restaurantId != 0)
      {
        _db.RestaurantTags.Add(new RestaurantTag() { RestaurantId = restaurantId, TagId = tag.TagId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = tag.TagId });
    }
    public ActionResult Edit(int id)
    {
      Tag thisTag = _db.Tags.FirstOrDefault(tag => tag.TagId == id);
      return View(thisTag);
    }
    [HttpPost]
    public ActionResult Edit (Tag tag)
    {
      _db.Tags.Update(tag);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Delete(int id)
    {
      Tag thisTag = _db.Tags.FirstOrDefault(tag => tag.TagId == id);
      return View(thisTag);
    }
    [HttpPost, ActionName("Delete")]
     public ActionResult DeleteConfirmed(int id)
    {
      Tag thisTag = _db.Tags.FirstOrDefault(tags => tags.TagId == id);
      _db.Tags.Remove(thisTag);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      RestaurantTag joinEntry = _db.RestaurantTags.FirstOrDefault(entry => entry.RestaurantTagId == joinId);
      _db.RestaurantTags.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Eateries/Views/Restaurants/AddTag.cshtml
@{
  Layout = "_Layout";
}

@model Eateries.Models.Restaurant

<h2>Add a tag</h2>

<h4>Add a tag to this item: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.RestaurantId)

  @Html.Label("Select tag")
  @Html.DropDownList("TagId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

Eateries/Views/Restaurants/Create.cshtml
@{
  Layout = "_Layout";
}

@model Eateries.Models.Restaurant

<p><strong>NOTE:</strong> You need to have at least one cuisine before you can add an eatery!</p>
<p>Go to @Html.ActionLink("this page", "Create", "Cuisine") to create a cuisine.</p>

<h4>Add a new restaurant</h4>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  @Html.LabelFor(model => model.Description)
  @Html.TextBoxFor(model => model.Description)

  @Html.LabelFor(model => model.Cuisine)
  @Html.DropDownList("CuisineId")

  <input type="submit" value="Add new restaurant" class="btn btn-primary" />
}
<p>@Html.ActionLink("Show all restaurant", "Index")</p>

Eateries/Views/Restaurants/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Eateries.Models.Restaurant
<h2>Are you sure you want to delete this?</h2>
@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

Eateries/Views/Restaurants/Details.cshtml
@{
  Layout = "_Layout";
}

@using Eateries.Models
@model Eateries.Models.Restaurant

<h2>Restaurant Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)<h3>
    <h3>@Html.DisplayNameFor(model => model.Cuisine): @Html.DisplayFor(model => model.Cuisine.Name)<h3>

        @if (@Model.JoinEntities.Count == 0)
        {
          <p>This restaurant does not have any tags yet!</p>
        }
        else
        {
          <h4>This restaurant has the following tags:</h4>
          <ul>
            @foreach (RestaurantTag join in Model.JoinEntities)
            {
              <li>Tag: @join.Tag.Title</li>
              @using (Html.BeginForm("DeleteJoin", "Restaurants"))
              {
                @Html.Hidden("joinId", @join.RestaurantTagId)
                <input type="submit" value="Delete" />
              }
            }
          </ul>
        }
        <p>@Html.ActionLink("Back to list", "Index")</p>
        <p>@Html.ActionLink("Edit restaurant or cuisine", "Edit", new { id = Model.RestaurantId })</p>
        <p>@Html.ActionLink("Add a Tag", "AddTag", new { id = Model.RestaurantId })</p>
        <p>@Html.ActionLink("See all tags", "Index", "Tags")</p>
        <p>@Html.ActionLink("Delete restaurant", "Delete", new { id = Model.RestaurantId })</p>

Eateries/Views/Restaurants/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Eateries.Models.Restaurant

<h2>Edit</h2>

<h4>Edit this restaurant: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.RestaurantId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)
  @Html.LabelFor(model => model.Description)
  @Html.EditorFor(model => model.Description)

  @Html.LabelFor(model => model.Cuisine)
  @Html.DropDownList("CuisineId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

Eateries/Views/Restaurants/Index.cshtml
@{
  Layout = "_Layout";
}

@using Eateries.Models;

<h1>Restaurants</h1>

@if (@Model.Count == 0)
{
  <h3>No restaurants have been added yet!</h3>
} 

<ul>
  @foreach(Restaurant restaurant in Model)
  {
    <li>@Html.ActionLink($"{restaurant.Name}", "Details", new { id = restaurant.RestaurantId })</li>
  }
</ul>

<p>@Html.ActionLink("Add new cuisine", "Create")</p>
<p>@Html.ActionLink("Add new restaurant", "Create", "Restaurants")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>